---
# tasks file for roles/add-user

- name: ensure sudo group exits
  group:
    name: sudo
    state: present


- name: add the edg user to the system
  action: user name={{ edg_user }} password={{ edg_password }} update_password=always shell=/bin/bash home=/home/{{ edg_user }} groups=sudo append=yes

- name: add edg to the suders file
  lineinfile: "dest=/etc/sudoers state=present regexp='^%edg' line='%edg ALL=(ALL) NOPASSWD: ALL'"
